config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :products do
    member do
      get :new_movement
      post :create_movement
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :product
  MovementTypes = {add: 0, remove: 1}
  validates :movement_quantity, presence: true, numericality: true

  def self.get_movement_types
    {
      "Add" => MovementTypes[:add],
      "Remove" => MovementTypes[:remove]
    }
  end

  def movement_type_name
    case movement_type
    when MovementTypes[:add]
      "Add"
    when MovementTypes[:remove]
      "Remove"
    else
      "Unknown"
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :movements, dependent: :destroy
  validates :name, presence: true
  validates :reference, presence: true

  def quantity
    total = 0
    self.movements.each do |movement|
      if movement.movement_type == Movement::MovementTypes[:add]
        total += movement.movement_quantity
      else
        total -= movement.movement_quantity
      end
    end
    total
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="Products.xlsx"'
      }
    end
  end

  # GET /products/1 or /products/1.json
  def show
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="Product_details.xlsx"'
      }
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def new_movement
    @product = Product.find(params[:id])
    @movement = Movement.new
  end

  def create_movement
    @product = Product.find(params[:id])
    @movement = Movement.new(movement_params)
    @movement.product_id = @product.id
    if @movement.save
      redirect_to @product, notice: "Movement was successfully created."
    else
      flash[:notice] = "An error has occurred. Movement was not created."
      render :new_movement, status: :unprocessable_entity
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :reference, :description)
    end

    def movement_params
      params.require(:movement).permit(:movement_quantity, :movement_type, :comment)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom fonts for this template-->
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
 
 <script src="https://kit.fontawesome.com/8bfb3ed134.js" crossorigin="anonymous"></script>
 
  </head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= root_path %>">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fa-solid fa-industry"></i>
                    
                </div>
                <div class="sidebar-brand-text mx-3">Inventory Control System <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
        <!--    <li class="nav-item">
                <a class="nav-link" href="<%= root_path %>">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            -->

            <li class="nav-item">
                <a class="nav-link" href="<%= products_path %>">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Products</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
       <!--     <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>   -->

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                      <%= yield %>
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>



</html>

app/views/products/_form.html.erb
<div class="form-group">
  <div class="col-lg-12">
    <div class="card p-5">

      <%= form_with(model: product) do |form| %>
        <% if product.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

            <ul>
              <% product.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name, style: "display: block" %>
          <%= form.text_field :name, class: "form-control", placeholder: "Name" %>
        </div>

        <div class="form-group">
          <%= form.label :reference, style: "display: block" %>
          <%= form.text_field :reference, class: "form-control", placeholder: "Reference"  %>
        </div>

        <div class="form-group">
          <%= form.label :description, style: "display: block" %>
          <%= form.text_area :description, class: "form-control" %>
        </div>

        <div>
          <%= form.submit "Send", class: "btn btn-primary"%>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Reference:</strong>
    <%= product.reference %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product, class: "btn btn-primary" %> |
  <%= link_to "Back to products list", products_path, class: "btn btn-warning" %>
</div>

app/views/products/index.html.erb
<h1>Products List</h1>

<a href="<%= new_product_path %>" class="btn btn-primary btn-icon-split">
<span class="icon text-white-50">
<i class="fas fa-flag"></i>
</span>
<span class="text">Create new product</span>
</a>

<%= link_to 'Export to Excel', products_path(format: :xlsx), class: "btn btn-success" %>

<br>
<table class="table">
<thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Reference</th>
    <th>Quantity</th>
    <th>Actions</th>
  </tr>
<tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.name %></td>
      <td><%= product.reference %></td>
      <td><%= product.quantity %></td>
      <td><%= link_to 'Details', product_path(product), class: "btn btn-primary" %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/products/new.html.erb
<h1>Create new product</h1>
<%= link_to "Back to products list", products_path, class: "btn btn-primary" %>
<br>
<br>
<%= render "form", product: @product %>

app/views/products/new_movement.html.erb
<h1>Create movement</h1>
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <table class="table">
        <tr>
          <td><b>Name:</b></td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td><b>Reference:</b></td>
          <td><%= @product.reference %></td>
        </tr>

      </table>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      <%= form_with model: @movement, url: create_movement_product_path(@product), method: :post do |f| %>
       
        <% if @movement.errors.any? %>
        <div class="alert alert-danger">
          <h3><%= flash[:notice] %></h3>
          <ul>
            <% @movement.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <div class="form-group">
          <%= f.label :movement_type, "Movement_type" %>
          <%= f.select :movement_type, options_for_select(Movement.get_movement_types), {}, {class: "form-control"} %>
        </div>

        <div class="form-group">
          <%= f.label :movement_quantity, "Quantity" %>
          <%= f.number_field :movement_quantity, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :comment, "Comment" %>
          <%= f.text_area :comment, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit "Create movement", class: "btn btn-primary" %>
          <%= link_to "Cancel", product_path(@product), class: "btn btn-danger" %>
        </div>
      
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Product details</h1>
    <%= link_to "Back to products list", products_path, class: "btn btn-primary" %>
    <%= link_to "Edit this product", edit_product_path(@product), class: "btn btn-primary" %>
    <%= link_to "Destroy this product", @product, method: :delete, class: "btn btn-danger" %>
    <%= link_to "Create movement", new_movement_product_path(@product), class: "btn btn-success" %>
    <%= link_to "Export to Excel", product_path(@product, format: :xlsx), class: "btn btn-success" %>

    <div class="card">
      <table class="table">
        <tr>
          <th>Product name</th>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <th>Product reference</th>
          <td><%= @product.reference %></td>
        <tr>
          <th>Product description</th>
          <td><%= @product.description %></td>
        </tr>
        <tr>
          <th>Product quantity</th>
          <td><%= @product.quantity %></td>
        </tr>
        <tr>
          <th>Creation date</th>
          <td><%= @product.created_at %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<div class="row" style="margin-top: 20px">
  <div class="col-lg-12">
    <div class="card" style="padding-top: 20px">
      <h1>Movements</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Type</th>
            <th>Quantity</th>
            <th>Comment</th>
            <th>Date/Time</th>
          </tr>
        </thead>
        <tbody>
          <% @product.movements.each do |movement| %>
            <tr>
              <td><%= movement.movement_type_name %></td>
              <td><%= movement.movement_quantity %></td>
              <td><%= movement.comment %></td>
              <td><%= movement.created_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>